<?php
/*
 * @file
 * Implements the CyCo events log module.
 */

require_once realpath( dirname(__FILE__) . '/cyco_events_views.inc' );

/**
 * Implements hook_help().
 */
function cyco_events_log_help($path, $arg) {
  switch ($path) {
    case 'admin/help#cyco_events_log':
      return '<p>' . t('Helpy helpy help help, <a href="@jquery">jQuery</a>.', 
          array(
            '@jquery' => 'http://jquery.com',
          )) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function cyco_events_log_permission() {
  return array(
    'toggle event logging' => array(
      'title' => t('Toggle event logging'),
      'description' => t('User is able to turn event logging on and off.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function cyco_events_log_menu() {
  $items = array();
  //Toggle event logging.
  $items['toggle-event-logging'] = array(
    'page callback' => '_cyco_events_log_toggle_event_logging',
    'access callback' => 'user_access',
    'access arguments' => array('toggle event logging'),
  );
  return $items;
}

/**
 * Implementation of hook_views_api().
 */
function cyco_events_log_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'cyco_events_log'),
    'template path' => drupal_get_path('module', 'cyco_events_log') . '/templates',
  );
}

/**
 * Implements hook_init.
 * 
 * Set a JS var to show whether events should be logged.
 */
function cyco_events_log_init() {
  drupal_add_js(
      array('cycoLogEvents' => 
        array('logEvents' => _cyco_events_log_get_should_log_events()) ),
      'setting'
  );
  if ( _cyco_events_log_get_should_log_events() == 'yes' ) {
    drupal_add_js(
      drupal_get_path('module', 'cyco_events_log') . '/js/cyco_events_log.js'
//      array('type' => 'file', 'preprocess' => TRUE,)
    );    
  }
}

/**
 * Implements hook_page_build.
 */
function cyco_events_log_page_build(&$page) {
  //Show log in reminder.
  _cyco_events_show_log_in_reminder();
  if ( _cyco_events_log_should_log_events() ) {
    //Log page view.
    cyco_events_log_log_page_view();
    //Send logging data to JS, to log page leaving event.
    drupal_add_js(
        array('cycoLogEvents' => 
          array(
            'eventType' => 'leave_page',
            'path' => current_path(),
          ) 
        ),
        'setting'
    );
  }
}

/**
 * For anonymous, show a reminder to log in.
 */
function _cyco_events_show_log_in_reminder() {
  global $user;
  //Only show for anon.
  if ( $user->uid == 0 ) {
    $subsequent_destination = base_path() . current_path();
    $link = l(t('login'), 'user/login', array('query' => array('destination' => $subsequent_destination)));
    $message = t('If you are a student, please ' . $link . t('.'));
    drupal_set_message($message);
  }
}

/**
 * Log a page view.
 */
function cyco_events_log_log_page_view() {
  if ( _cyco_events_log_should_log_events() ) {
    global $user;
    $path = current_path();
    $bundle = 'view_page';
    $user_link = l($user->name, 'users/' . $user->name);
    $path_link = l($path, $path);
    $summary = t('User ') . $user_link . t(' viewed ') . $path_link;
    //Log.
    $entity_type = 'cyco_event';
    $entity = entity_create($entity_type, array('type' => $bundle));
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    $wrapper->uid = $user->uid;
    if ( isset($wrapper->field_summary) ) {
      $wrapper->field_summary->set( 
          array('value' => $summary,
            'format'=>'limited_html',
          )
      );
    }
    if ( isset($wrapper->field_path) ) {
      $wrapper->field_path->set( $path );
    }
    $wrapper->save();
  }
}

/**
 * Log leaving a page. Called from JS through Services.
 */
function cyco_events_log_log_page_leaving($data) {
  if ( _cyco_events_log_should_log_events() ) {
    global $user;
    $path = $data['path'];
    $bundle = 'leave_page';
    $user_link = l($user->name, 'users/' . $user->name);
    $path_link = l($path, $path);
    $summary = t('User ') . $user_link . t(' left ') . $path_link;
    //Log.
    $entity_type = 'cyco_event';
    $entity = entity_create($entity_type, array('type' => $bundle));
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    $wrapper->uid = $user->uid;
    if ( isset($wrapper->field_summary) ) {
      $wrapper->field_summary->set( 
          array('value' => $summary,
            'format'=>'limited_html',
          )
      );
    }
    if ( isset($wrapper->field_path) ) {
      $wrapper->field_path->set( $path );
    }
    $wrapper->save();
    return 'OK';
  }
}

//function cyco_events_log_node_view($node, $view_mode, $langcode) {
//  if ( _cyco_events_log_get_should_log_events() == 'yes' ) {
//    drupal_add_js(
//        array('cycoLogEvents' => 
//          array(
//            'eventType' => 
//            'nid' => $node->nid,
//          ) 
//        ),
//        'setting'
//    );
//    
//  }
//  
//}

/**
 * Log an Other event. Called by JS, through Services.
 * @param type $data
 * @return string Status, OK for OK.
 */
function cyco_events_log_log_other_event($data) {
  if (_cyco_events_log_should_log_events() ) {
//    drupal_add_js(
//      drupal_get_path('module', 'cyco_events_log') . '/js/cyco_events_log.js'
////      array('type' => 'file', 'preprocess' => TRUE,)
//    );
    global $user;
    //Extract data.
    $bundle = $data['bundle'];
    $activity_type = $data['activityType'];
    $summary = $data['summary'];
    $params = $data['params'];
    //Log.
    $entity_type = 'cyco_event';
    $entity = entity_create($entity_type, array('type' => $bundle));
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    $wrapper->uid = $user->uid;
    if ( isset($wrapper->field_summary) ) {
      $wrapper->field_summary->set( 
          array('value' => $summary,
            'format'=>'limited_html',
          )
      );
    }
    if ( isset($wrapper->field_activity_type) ) {
      $wrapper->field_activity_type->set( $activity_type );
    }
    if ( isset($wrapper->field_activity_params) ) {
      $wrapper->field_activity_params->set( $params );  
    }
    $wrapper->save();
    return 'OK';
  }
}



/**
 * Should log events? Yes, iff global logging var is on, and user is a 
 * student in a class where logging is on.
 * @return string yes or no.
 */
function _cyco_events_log_get_should_log_events() {
  $logging_on = &drupal_static(__FUNCTION__); 
  if ( ! isset($logging_on) ) {
    $logging_on = 'no'; //Init, change to yes if logging should be on.
    $global_logging = variable_get('cyco_event_logging', 'off');
    if ( $global_logging == 'on' ) {
      global $user;
      if (cyco_core_user_has_role($user, 'student') ) {
        $group_ids = og_get_groups_by_user($user, 'node');
        foreach( $group_ids as $group_id ) {
          $group = node_load( $group_id );
          if ( $group->type == 'class' ) {
            $log_events = field_get_items('node', $group, 'field_log_events');
            if ( $log_events[0]['value'] == 1 ) {
              $logging_on = 'yes';
              break;
            }
          }
        }
      } //End user is student.
    } //end global logging is on.
  } //var not cached.
  return $logging_on;
}

/**
 * Should log events?
 * @return boolean True if event logging is on, and the current user is a student.
 */
function _cyco_events_log_should_log_events() {
  return ( _cyco_events_log_get_should_log_events() == 'yes' );
}

/**
* Implements hook_services_resources().
 * 
 * Define all the services for the exercises module.
*/
function cyco_events_log_services_resources() {
  $api = array(
    /** Should save events flag. **/
    'event_logging' => array(
      'actions' => array(
//        'shouldLogEvents' => array(
//          'help' => t('Return yes/no, whether should log events for this user.'),
//          'access arguments' => array('access content'),
//          'callback' => '_cyco_events_log_get_should_log_events',
//        ),
        'logOtherEvent' => array(
          'help' => t('Log an Other event.'),
          'access arguments' => array('access content'),
          'callback' => 'cyco_events_log_log_other_event',
          'args' => array(
            array(
             'name' => 'data',
             'type' => 'struct',
             'description' => 'Event log Other event',
             'source' => 'data',
             'optional' => FALSE,
             ),
           ), //End args.
        ), // End LogOtherEvent
        'logPageLeaveEvent' => array(
          'help' => t('Log a page leave event.'),
          'access arguments' => array('access content'),
          'callback' => 'cyco_events_log_log_page_leaving',
          'args' => array(
            array(
             'name' => 'data',
             'type' => 'struct',
             'description' => 'Event log Page leave event',
             'source' => 'data',
             'optional' => FALSE,
             ),
           ), //End args.
        ), // End logPageLeaveEvent
      ),
    ),
  );
  return $api;
}

/**
 * Implements hook_user_login().
 */
function cyco_events_log_user_login(&$edit, $account) {
  global $base_url;
  if ( _cyco_events_log_should_log_events() ) {
    //Log it.
    $entity_type = 'cyco_event';
    $entity = entity_create($entity_type, array('type' => 'log_in'));
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    $wrapper->uid = $account->uid;
    $wrapper->field_summary->set( 
        array('value' => t('Login by ') . '<a href="' . $base_url .'/users/' . $account->name 
          . '">' . $account->name . '</a>',
          'format'=>'limited_html',
        )
      );
    $wrapper->save();
  }
}

/**
 * Implements hook_user_login().
 */
function cyco_events_log_user_logout($account) {
  global $base_url;
  if ( _cyco_events_log_should_log_events() ) {
    //Log it.
    $entity_type = 'cyco_event';
    $entity = entity_create($entity_type, array('type' => 'log_out'));
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    $wrapper->uid = $account->uid;
    $wrapper->field_summary->set( 
        array('value' => t('Logout by ') . '<a href="' . $base_url .'/users/' . $account->name 
          . '">' . $account->name . '</a>',
          'format'=>'limited_html',
        )
      );
    $wrapper->save();
  }
}

/**
 * Log a node view in full mode. NOT a hook implementation.
 */
//function cyco_events_log_log_node_view($node, $view_mode, $langcode) {
//  global $base_url;
//  if ( _cyco_events_log_should_log_events() ) {
//    if ( $view_mode == 'full' ) {
//      //Log it.
//      $entity_type = 'cyco_event';
//      $entity = entity_create($entity_type, array('type' => 'view_node'));
//      $wrapper = entity_metadata_wrapper($entity_type, $entity);
//      global $user;
//      $wrapper->uid = $user->uid;
//      $user_name = ($user->uid === 0) ? 'Anonymous' : $user->name;
//      $node_link = '<a href="' . $base_url .'/node/' . $node->nid 
//            . '">' . $node->title . '</a>';
//      $user_link = '<a href="' . $base_url .'/users/' . $user_name 
//            . '">' . $user_name . '</a>';
//      $message = t('View ' . $node->type . ' node ') . $node_link . t(' by ') . $user_link . '.';
//      $wrapper->field_summary->set( 
//          array('value' => $message,
//            'format'=>'limited_html',
//          )
//        );
//      $wrapper->field_node->set( $node->nid );
//      $wrapper->save();
//    }
//  }
//}

/**
 * Toggle event logging.
 */
function _cyco_events_log_toggle_event_logging() {
  $logging = variable_get('cyco_event_logging', 'off');
  if ( $logging === 'on' ) {
    variable_set('cyco_event_logging', 'off');
    $message = t('Event logging is now off.');
  }
  else {
    variable_set('cyco_event_logging', 'on');
    $message = t('Event logging is now on.');
  }
  drupal_set_message( $message );
  drupal_goto('control-panel');
}

/**
 * Implements hook_webform_select_options_info.
 * @return array Prebuilt option lists for Webform that are to be defined.
 */
function cyco_events_log_webform_select_options_info() {
  drupal_set_message('dog');
  $lists = array();
  $lists['agree_disagree_7'] = array(
    'title' => t('Agree/disagree - 7-point'),
    'options callback' => '_cyco_events_log_agree_disagree_7_point_labels',    
  );
  return $lists;
}

/**
 * Define prebuilt option list for Webform with 7-point agree/disagree scale.
 * @return array Options.
 */
function _cyco_events_log_agree_disagree_7_point_labels($component, $flat, $arguments) {
  $options = array();
  $options = array(
    7 => 'Strongly agree',
    6 => 'Agree',
    5 => 'Somewhat agree',
    4 => 'Neither agree nor disagree',
    3 => 'Somewhat disagree',
    2 => 'Disagree',
    1 => 'Strongly disagree',
  );
  return $options;
}
