<?php
/**
 * @file
 * cyco_exercises_model_solutions.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function cyco_exercises_model_solutions_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_exercise_solved'
  $field_bases['field_exercise_solved'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_exercise_solved',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'direction' => 'ASC',
          'property' => 'title',
          'type' => 'property',
        ),
        'target_bundles' => array(
          'exercise' => 'exercise',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
