<?php

function cyco_test_menu() {
  $items = array();
  $items['t1'] = array(
    'title' => 'Test',
    'page callback' => '_test_t1',
    'access arguments' => array('administer content types'),
  );
  $items['t2'] = array(
    'title' => 'Test ',
    'page callback' => '_test_t2',
    'access callback' => TRUE,
  );
  return $items;
}

function _test_t1() {
  $path = 'node/add/exercise-submission';
  $page_callback_result = menu_execute_active_handler($path, FALSE);
  $result =  drupal_render( $page_callback_result );
  
// Is we have an array, lets assume we need to render it out.
  if (is_array($page_callback_result)) {
    if (isset($page_callback_result['nodes'])) {
      foreach ($page_callback_result['nodes'] as $nid => $tmpNode) {
        if (isset($tmpNode['#view_mode'])) {
          $node_view = $tmpNode['#node'];
          $node_view_array = node_view($node_view, 'colorbox');
          if (module_exists('comment')) {
            $node_view_array['comments'] = comment_node_page_additions($node_view);
          }
          $rendered_node = drupal_render($node_view_array);
          $page_callback_result['nodes'][$nid] = array('#markup' => $rendered_node);
        }
      }
    }
  }
  
  print '<h1>DOG</h1>' . $result;
  die();
}

function cyco_test_form_exercise_submission_node_form_alter( &$form, $form_state) {
  $r=4;
  
}

function _test_t2() {
  $uid = 1;
  $role = 'grader';
  $is_admin = cyco_core_user_has_role( $uid, $role );
  $result = '<p>User ' . $uid . ' does ' . ( $is_admin ? '' : 'not ' ) 
      . 'have the ' . $role . ' role';
  return $result;
}