<?php

function cyco_test_menu() {
  $items = array();
  $items['dog'] = array(
    'title' => 'Import',
    'page callback' => 'cyco_run_test',
    'access arguments' => array('administer pseudents'),
  );
  return $items;
}

function cyco_run_test() {
  $file_name = drupal_get_path('module', 'cyco_test') . '/test.export';
  $data = file_get_contents($file_name);
  $messages = node_export_import($data);
  drupal_set_message('<pre>' . print_r($messages, TRUE) . '</pre>');
  return 'Dog';
}
