<?php
/**
 * Flag showing whether the poses preview data (used with CKEditor) is dirty.
 */
define('POSES_PREVIW_DIRTY_FLAG_VAR', 'pseudents_poses_preview_dirty');
/**
 * Poses preview data used with CKEditor.
 */
define('POSES_PREVIEW_DATA_VAR', 'pseudents_poses_preview_data');


//function pseudents_init() {
//  drupal_add_css(
//    drupal_get_path('module', 'pseudents') . '/css/pseudents.css'
//  );
//}

/**
 * Implements hook_help().
 */
function pseudents_help($path, $arg) {
  switch ($path) {
      // Help for another path in the block module
    case 'admin/help#pseudents':
      return '<p>' . t('Helpy help help, <a href="@jquery">jQuery</a>.', 
          array(
            '@jquery' => 'http://jquery.com',
          )) . '</p>';
  }
}

function pseudents_menu() {
  $items = array();
  $items['admin/config/cybercourse/pseudents'] = array(
    'title' => 'Pseudents',
    'description' => 'Pseudents configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pseudents_admin_form'),
    'access arguments' => array('administer pseudents'),
  );
  return $items;
}

function pseudents_admin_form($form, &$form_state) {
  $form['clear_cache'] = array(
    '#type' => 'submit',
    '#value' => t('Clear pseudent cache'),
    '#submit' => array('pseudents_flush_cache'),
  );  
  return $form;
}

function pseudents_flush_cache() {
  _pseudents_generate_ck_pseudent_table();
  drupal_set_message( t('Pseudent cache cleared.') );
  drupal_goto('admin/config/cybercourse/pseudents');
}

/**
 * Register the CKEditor plugin.
 */
function pseudents_ckeditor_plugin() {
  return array(
    'pseudent' => array(
      // Plugin name.
      'name' => 'pseudent',
      // Plugin description - it will be displayed in the plugins management section of the profile settings.
      'desc' => t('Cyco: Insert a pseudent into content.'),
      // The full path to the CKEditor plugin directory, trailing slash included.
      'path' => drupal_get_path('module', 'pseudents') . '/plugin/',
    )
  );
}

function pseudents_swim_load_ck_plugins() {
  global $base_url;
  $result = array(
    'name' => 'insert_pseudent',
    'path' => $base_url . '/' . drupal_get_path('module', 'pseudents') 
        . '/ck_plugins/insert_pseudent/',
  );
  return $result;
}

/**
 * Implementation of hook_perm().
 */
function pseudents_permission() {
  return array(
    'administer pseudents' => array(
      'title' => t('Administer pseudents'),
      'description' => t('Create, delete, and update pseudents.')
    ),
//    'use pseudents in content' => array(
//      'title' => t('Use pseudents in content'),
//      'description' => t('Insert pseudent token in content.')
//    ),
  );
}


function pseudents_get_editor_previews() {
  $pseudents_preview_dirty = variable_get(POSES_PREVIW_DIRTY_FLAG_VAR, TRUE);
  if ( $pseudents_preview_dirty ) {
    _pseudents_generate_ck_pseudent_table();
  }
  return variable_get(POSES_PREVIEW_DATA_VAR, 'none');
}

/**
 * Generate HTML for a table of pseudent poses to use in a CKEditor dialog.
 * The result is cached. 
 */
function _pseudents_generate_ck_pseudent_table() {
  //Fetch pseudent pose data.
  $query = new EntityFieldQuery;
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'pseudent_pose')
    ->propertyCondition('status', 1)
    ->propertyOrderBy('title');
  $query_result = $query->execute();
  //Create the pseudent HTML.
  $pseudents = array();
  if ( isset($query_result['node']) ) {
    //Get term names.
    $term_names = _pseudents_load_category_terms();
    foreach ( $query_result['node'] as $nid => $value ) {
      $node = node_load($nid);
      $title = $node->title;
      $notes = swim_render_field( $node, 'field_body', 'summary-or-trimmed');
      //Caption is not a required field.
      if ( isset($node->field_caption[LANGUAGE_NONE][0]['safe_value']) ) {
        $caption = $node->field_caption[LANGUAGE_NONE][0]['safe_value'];
      }
      else {
        $caption = '';
      }
      $categories = array();
      if ( isset($node->field_pseudent_categories[LANGUAGE_NONE]) ) {
        foreach( $node->field_pseudent_categories[LANGUAGE_NONE] as $term ) {
          $categories[ $term['tid'] ] = $term_names[ $term['tid'] ];
        }
      }
      $usable_url = _pseudents_uri_2_path(
          $node->field_image[LANGUAGE_NONE][0]['uri']
      );
      $pseudents[$nid] = array(
        'nid' => $nid,
        'title' => $title,
        'url' => $usable_url,
        'caption' => $caption,
        'categories' => $categories,
      );
    } // end for
  }
  if ( $pseudents == '' ) {
    variable_set(POSES_PREVIEW_DATA_VAR, 'none');
  }
  else {
    variable_set( POSES_PREVIEW_DATA_VAR, $pseudents );
  }
  variable_set(POSES_PREVIW_DIRTY_FLAG_VAR, FALSE);
}

/** 
 * Find the names of all the terms in the pseudent_categories vocab.
 * 
 * @return array Term names, indexed by term id
 */
function _pseudents_load_category_terms() {
  $name = 'pseudent_categories';
  $myvoc = taxonomy_vocabulary_machine_name_load($name);
  $tree = taxonomy_get_tree($myvoc->vid);
  $term_names = array();
  foreach ($tree as $term) {
   $term_names[ $term->tid ] = $term->name;
  }
  return $term_names;
}

/*
 * Set 'cache is dirty' flag when poses change.
 */
function pseudents_node_update( $node ) {
  _pseudents_set_dirty_flag( $node );
}

function pseudents_node_delete( $node ) {
  _pseudents_set_dirty_flag( $node );
}

function pseudents_node_insert( $node ) {
  _pseudents_set_dirty_flag( $node );
}

function _pseudents_set_dirty_flag( $node ) {
  if ( $node->type == 'pseudent_pose' ) {
    //Mark pseudent pose preview data used in editor as dirty.
    variable_set(POSES_PREVIW_DIRTY_FLAG_VAR, TRUE);
  }  
}

function pseudents_form_alter(&$form, &$form_state, $form_id) {
  // @todo Instead of checking form_id, check for a field
  //having the SWIM format? Cache the results of the check 
  //so don't run check again on this page call.
  //Not sure if this is the right approach.
  if ( strpos($form_id, 'node_form') !== FALSE ) {
    _pseudents_load_client_side_stuff();
  }
  if ( $form_id == 'pseudent_pose_node_form' ) {
    $form['pseudent_pose_link'] = array(
        '#type' => 'markup',
        '#markup' => _pseudents_make_link2list(),
        '#weight' => ( $form['field_body']['#weight'] + 1 ),
    );    
  }
}

/**
 * Make a link back to the pseudent list page.
 */
function _pseudents_make_link2list() {
  return 
        '<div class="pseudents-back-link">'
      .   l(
            '<< Back to pseudents list', 
            'pseudent-poses'
          )
      . '</div>';  
}

/**
 * Add client-side stuff the pseudent code needs.
 */
function _pseudents_load_client_side_stuff() {
  //Only run this once per page.
  static $already_added = FALSE;
  if ( $already_added ) {
    return;
  }
  $already_added = TRUE;
  drupal_add_css(drupal_get_path('module', 'pseudents') . '/css/pseudents.css' );
  global $base_url;
  $css_path = $base_url . '/' . drupal_get_path('module', 'pseudents') . '/css/';
  $settings = array(
    'posePreviews' => pseudents_get_editor_previews(),
    'poseStylesheet' => $css_path . 'pseudents.css',
    'poseStylesheetEdit' => $css_path . 'pseudents_edit.css',
  );
  drupal_add_js(
      array('pseudents' => $settings),
      'setting'
  );
}

/**
 * Implement hook_swim_add_client_stuff().
 * 
 * SWIM calls this to let modules load their own client-side stuff.
 */
function pseudents_swim_add_client_stuff() {
  _pseudents_load_client_side_stuff();
}


/**
 * Implements hook_swim_ckhtml_2_directive_alter().
 * @param string $content Content to change.
 */
function pseudents_swim_ckhtml_2_directive_alter( &$content ) {
  $regex = 
      '/\<div class\=\"pseudent\".*?data\-pseudent\-id\=\"(.*?)\"*.\>\s*'
      .  '\<div class\=\"pseudent\-image\-container\"\>\s*'
      .    '\<img.*?\>\s*'
      .    '\<div class\=\"pseudent-image-caption\"\>.*?\<\/div\>\s*'
      .  '\<\/div\>\s*'
      .  '\<div class=\"pseudent\-content\"\>(.*?)\<\/div\>\s*'
      . '\<\/div\>/is';
    //? for lazy eval.
    //s option to include new lines in whitespace matches.
  $content
    = preg_replace_callback($regex, '_pseudents_make_directive_replacements', $content);
}

function _pseudents_make_directive_replacements($matches) {
  $nid = $matches[1];
  $content = $matches[2];
  //Add four spaces after every new line in the content, because indentation
  //is significant in ReST.
  $content = str_replace("\n", "\n    ", $content);
  $replacement = 
      '.. pseudent:: ' . $nid . "\n\n"
    . '    ' . $content . "\n\n";
  return $replacement;
}

/**
 * Implements hook_restructuredtext_to_html_alter.
 * 
 * Translate intermediate (betwixt) markup in $content (as inserted by
 * custom ReST directive) to its HTML equivalent. Sample betwixt markup:
 * 
 * [[[animal 666|||note]]]
 * 
 */
function pseudents_restructuredtext_to_html_alter(&$content) { 
  $regex = 
      '/\[\[\[cycopseudent\s*(\d*?)\|\|\|(.*?)\]\]\]/is';
  //? is for lazy match.
      //s option so it can contain new line chars.
  $content
    = preg_replace_callback($regex, '_pseudents_make_view_replacements', $content);
}

function _pseudents_make_view_replacements($matches) {
  $nid = $matches[1];
  $content = $matches[2];
  //Load pseudent data.
  $node = node_load($nid);
  if ( !$node ) {
    $message = '_pseudents_make_view_replacements: bad nid: ' . $nid;
    watchdog('pseudents', $message);
    throw new Exception($message);
  }
  $caption = '';
  if (sizeof( $node->field_caption ) > 0 ) {
    $caption = $node->field_caption[LANGUAGE_NONE][0]['value'];
  }
  $usable_url = _pseudents_uri_2_path(
     $node->field_image[LANGUAGE_NONE][0]['uri']
  );
  $html =   '<div class="pseudent">'
          .   '<div class="pseudent-image-container">'
          .     '<img class="pseudent-image" '
          .         'src="' . $usable_url . '" '
          .         'alt="' . $caption . '" >'
          .     '<div class="pseudent-image-caption">' 
          .       $caption
          .     '</div>'
          .   '</div>'
          .   '<div class="pseudent-content">' . $content . '</div>'
          . '</div>';
  return $html;
}

/**
 * Convert a Drupal URI to a URL usable on the Web.
 * @param string $uri Drupal URI
 * @return string Usable URL
 */
function _pseudents_uri_2_path( $uri ) {
  $absolute_url = file_create_url( $uri );
  //Convert to local URL.
  //This will only work for Drupals in the root of sub/domain?
  $url = parse_url($absolute_url);
  $usable_url = $url['path'];
  return $usable_url;
}


function pseudents_node_view($node, $view_mode, $langcode) {
  global $base_url;
  if ( $node->type == 'pseudent_pose' ){
    if ( $view_mode == 'full' ) {
          $node->content['pseudent_pose_link'] = array(
              '#markup' => _pseudents_make_link2list(),
              '#weight' => ( $node->content['field_body']['#weight'] + 1 ),
          );
          $node->content['pseudent_pose_add_link'] = array(
              '#markup' =>
                  '<div class="pseudents-back-link">'
                .   l(
                      '<< Add pseudent pose', 
                      $base_url . '/node/add/pseudent-pose'
                    )
                . '</div>', 
              '#weight' => ( $node->content['field_body']['#weight'] + 2 ),
          );
    }
  }
}